// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

var inherits = require('util').inherits;
var Template = require('../../../../lib/ojster').Template; // normally path will be just 'ojster'

var Hobbies = function() {
	Template.apply(this, arguments);
};
inherits(Hobbies, Template);

Hobbies.prototype.renderBlockMain = function() { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>No hobbies detected.</div>'
	);
}; // @8:1

module.exports = Hobbies;
