// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

var inherits = require('util').inherits;
var Base = require('./base');
var Hobbies = require('./hobbies');

/** @constructor */
var Person = function() {
	Base.apply(this, arguments);
};
inherits(Person, Base);


// here is assumed that template will be compiled with goog.scope enabled
// some of features used will provide non-working code if goog.scope is not enabled
// i.g. function definition outside of block and using aliases

// fully qualified names cannot be used here, because node does not understand them



// usually code is enclosed into such a "tag"
function twistScore(value) {
    return value * 5 / 3;
};


// but beyond blocks code can be inserted just plain
Person.prototype.calculateScore = function(person) {
    return twistScore(person.score);
};

Person.prototype.renderBlockMain = function() { // @27:1
	var self = this;
	var d = this.data, vars = this.vars;

    // TODO bad example, need 'init' function instead
    vars.score = this.calculateScore(d); // vars is right place for template-level variables
    Base.prototype.renderBlockMain.call(this);

}; // @33:1

// code could be here too, almost anywhere

Person.prototype.renderBlockTitle = function() { // @37:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'Person #',
		self.escape(d.id) // @37:29
	);
}; // @37:40

Person.prototype.renderBlockScript = function() { // @39:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<script>'
	); // @41:1

	// seems like jslint tries to check code within 'script' tags even if it's part of string constant, so avoid it

	self.writer.write(
		'(function() {\n    // TODO good for node, but bad for goog\n    var settings = ',
		JSON.stringify(this.ctx.pageSettings), // @44:20
		'; // inserting JSON unescaped\n    ojster.example.page.initPage(settings);\n})();</script>'
	);
}; // @48:1

Person.prototype.renderBlockContent = function() { // @50:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<span>A</span><span>B</span>',
		' ',
		'<span>C</span><br />'
	); // @54:2
	self.renderBlockEcho('Hey there!'); // @54:2
	self.writer.write(
		'<div>Hello, '
	); // @55:17
	self.renderBlockFullName(); // @55:17
	self.writer.write(
		'!</div><div>Your score: ',
		self.escape(vars.score), // @56:22
		'</div><div>Your skills:</div>'
	); // @58:5

	this.renderBlockSkills();


	if (d.events && d.events.length) {

	self.writer.write(
		'<div>Your events:</div>'
	); // @61:9

	d.events.forEach(function(event) {

	self.renderBlockBeforeEvent(); // @62:13
	self.writer.write(
		'<div>',
		self.escape(event.Name), // @63:18
		'</div>'
	); // @64:13

	self.renderBlockAfterEvent(); // 'self' alias of 'this' can be used when needed


	});


	}


	// checking whitespaces compaction:

	self.writer.write(
		'<div>-', // @69:5
		' ',
		'-</div>' // @69:19
	); // @71:5
	new Hobbies(d, this.ctx).renderTo(self); // @71:5
}; // @72:1

Person.prototype.renderBlockFullName = function() { // @55:17
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		self.escape(d.firstName), // @55:40
		' ',
		self.escape(d.lastName) // @55:59
	);
}; // @55:76

Person.prototype.renderBlockBeforeEvent = function() { // @62:13
	var self = this;
	var d = this.data, vars = this.vars;
};

Person.prototype.renderBlockEcho = function(msg) { // @74:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		self.escape(msg) // @75:2
	);
}; // @76:1

Person.prototype.renderBlockSkills = function() { // @78:1
	var self = this;
	var d = this.data, vars = this.vars;

    if (vars.areSkillsRendered) {
        return;
    }

    vars.areSkillsRendered = true;

    if (!d.skills) {
        this.renderBlockNoSkills();
        return;
    }

    for (var i=0, l=d.skills.length; i < l; i++) {
        var skill = d.skills[i];

	self.renderBlockParametrized(i, l, skill); // @94:3
	self.writer.write(
		'<div>',
		self.escape(skill.name), // @97:14
		': ',
		self.escape(skill.value), // @97:33
		'</div>'
	); // @98:1

    }

}; // @101:1

Person.prototype.renderBlockParametrized = function(i, l, skill) { // @94:3
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>',
		self.escape(i), // @95:9
		' of ',
		self.escape(l), // @95:21
		' is &quot;',
		self.escape(skill.name), // @95:39
		'&quot;</div>'
	);
}; // @96:3

Person.prototype.renderBlockNoSkills = function() { // @103:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>You have no skills :(</div>'
	);
}; // @105:1

Person.prototype.renderBlockAfterEvent = function() { // @107:1
	var self = this;
	var d = this.data, vars = this.vars;
};

module.exports = Person;
