// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

var inherits = require('util').inherits;
var page = require('../page');
var Base = require('./base');
var Hobbies = require('./hobbies');

var Person = function() {
	Base.apply(this, arguments);
};
inherits(Person, Base);


// here is assumed that template will be compiled with goog.scope enabled
// some of features used will provide non-working code if goog.scope is not enabled
// i.g. function definition outside of block and using aliases



// usually code is enclosed into such a "tag"
function twistScore(value) {
    return value * 5 / 3;
};


// but beyond blocks code can be inserted just plain
Person.prototype.calculateScore = function(person) {
    return Person.twistScore(person.score);
};

Person.prototype.renderBlockMain = function() { // @26:1
	var self = this;
	var d = this.data, vars = this.vars;

    // TODO bad example, need 'init' function instead
    vars.score = this.calculateScore(d); // vars is right place for template-level variables
    ojster.example.templates.Base.prototype.renderBlockMain();

}; // @32:1

// code could be here too, almost anywhere

Person.prototype.renderBlockTitle = function() { // @36:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'Person #',
		self.escape(d.id) // @36:29
	);
}; // @36:40

Person.prototype.renderBlockScript = function() { // @38:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<script>'
	); // @40:1

	// seems like jslint tries to check code within 'script' tags even if it's part of string constant, so avoid it

	self.writer.write(
		'(function() {\n    // TODO good for node, but bad for goog\n    var settings = ',
		JSON.stringify(ctx.pageSettings), // @43:20
		'; // inserting JSON unescaped\n    ojster.example.page.initPage(settings);\n})();</script>'
	);
}; // @47:1

Person.prototype.renderBlockContent = function() { // @49:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Hello, '
	); // @50:17
	self.renderBlockFullName();
	self.writer.write(
		'!</div><div>Your score: ',
		self.escape(vars.score), // @51:22
		'</div><div>Your skills, '
	); // @52:23

	this.renderBlockFullName();

	self.writer.write(
		':</div>'
	); // @53:5

	this.renderBlockSkills();


	if (d.events && d.events.length) {

	self.writer.write(
		'<div>Your events:</div>'
	); // @56:9

	d.events.forEach(function(event) {

	self.renderBlockBeforeEvent();
	self.writer.write(
		'<div>',
		self.escape(event.Name), // @58:18
		'</div>'
	); // @59:13

	self.renderBlockAfterEvent(); // 'self' alias of 'this' can be used when needed


	});


	}


	// checking whitespaces compaction:

	self.writer.write(
		'-', // @64:5
		' ',
		'-' // @64:14
	); // @66:5

    // rendering other template in place:
    new Hobbies(this.ctx, d).renderTo(this);
    

	// possible but less effective:

	self.writer.write(
		new Hobbies(this.ctx, d).render() // @71:5
	);
}; // @72:1

Person.prototype.renderBlockFullName = function() { // @50:17
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		self.escape(d.firstName), // @50:40
		' ',
		self.escape(d.lastName) // @50:59
	);
}; // @50:76

Person.prototype.renderBlockBeforeEvent = function() { // @57:13
	var self = this;
	var d = this.data, vars = this.vars;
};

Person.prototype.renderBlockSkills = function() { // @74:1
	var self = this;
	var d = this.data, vars = this.vars;

    if (vars.areSkillsRendered) {
        return;
    }

    vars.areSkillsRendered = true;

    if (!d.skills) {
        this.renderBlockNoSkills();
        return;
    }

    for (var i=0, l=d.skills.length; i < l; i++) {
        var skill = skills[i];

	self.writer.write(
		'<div>',
		self.escape(skill.name), // @90:14
		': ',
		self.escape(skill.value), // @90:33
		'</div>'
	); // @91:1

    }

}; // @94:1

Person.prototype.renderBlockNoSkills = function() { // @96:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'You have no skills :('
	);
}; // @98:1

Person.prototype.renderBlockAfterEvent = function() { // @100:1
	var self = this;
	var d = this.data, vars = this.vars;
};

module.exports = Person;
