// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

var inherits = require('util').inherits;
var ojster = require('../../../..'); // normally here will be just 'ojster'

/** @constructor */
var SomeTool = function() {
	ojster.Template.apply(this, arguments);
};
inherits(SomeTool, ojster.Template);
SomeTool.prototype.renderBlockMain = function() { // @5:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Some tool</div>'
	);
}; // @7:1

/** @constructor */
var SomeOtherTool = function() {
	ojster.Template.apply(this, arguments);
};
inherits(SomeOtherTool, ojster.Template);
SomeOtherTool.prototype.renderBlockMain = function() { // @11:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Other tool</div>'
	);
}; // @13:1

module.exports = {
	SomeTool: SomeTool,
	SomeOtherTool: SomeOtherTool
};
