// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
define(['ojster', './my_lib'], function (ojster, MyLib) {
"use strict";

// variables can be safely defined at any place
// they are bound to produced module only
var tmp;

// the same is true for functions
function abc() {
	return 'abc';
}


// @require needs path and optional subpath, fully qualified names can be provided for browser global
 // equivalent to: ojster = 'ojster'


// @template and @inherits need alias only
var Base = function(opt_data, opt_ctx, opt_writer) {
	ojster.Template.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Base, ojster.Template);


// any code within and outside of blocks can use any of aliases defined above
var tmp1 = Base.prototype;


Base.prototype.renderBlockMain = function() { // @25:1
	var self = this;
	var d = this.data, vars = this.vars;
};

return Base;

});
