// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('ojster.examples.templates.Base');

goog.require('ojster');

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {ojster.StringWriter=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
ojster.examples.templates.Base = function (opt_data, opt_ctx, opt_writer) {
	ojster.examples.templates.Base.base(this, 'constructor', opt_data, opt_ctx, opt_writer);
};
goog.inherits(ojster.examples.templates.Base, ojster.Template);

ojster.examples.templates.Base.prototype.renderBlockMain = function () { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'It is a base'
	);
}; // @8:1

ojster.examples.templates.Base.prototype.renderBlockFoo = function (a) { // @10:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'foo ',
		self.escape(a) // @11:9
	);
}; // @12:1
