// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('ojster.examples.templates.Child');

goog.require('ojster.examples.templates.Base');

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {ojster.StringWriter=} opt_writer
 * @constructor
 * @extends {ojster.examples.templates.Base}
 */
ojster.examples.templates.Child = function (opt_data, opt_ctx, opt_writer) {
	ojster.examples.templates.Child.base(this, 'constructor', opt_data, opt_ctx, opt_writer);
};
goog.inherits(ojster.examples.templates.Child, ojster.examples.templates.Base);

ojster.examples.templates.Child.prototype.renderBlockMain = function () { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	ojster.examples.templates.Child.base(this, 'renderBlockMain'); // @7:5
}; // @8:1

ojster.examples.templates.Child.prototype.renderBlockFoo = function (a) { // @10:1
	var self = this;
	var d = this.data, vars = this.vars;
	ojster.examples.templates.Child.base(this, 'renderBlockFoo', a); // @11:5
}; // @12:1
