// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
(function (root, factory) {
	"use strict";
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(['../../../../lib'], factory);
	} else {
		// Browser globals
		root.ojster = factory(root.ojster);
	}
}(this, function (ojster) {
"use strict";
 // normally here will be just 'ojster'

var Hobbies = function(opt_data, opt_ctx, opt_writer) {
	ojster.Template.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Hobbies, ojster.Template);

Hobbies.prototype.renderBlockMain = function() { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>No hobbies detected.</div>'
	);
}; // @8:1

return Hobbies;

}));
