"use strict";
var options = {
	intro: '// Content below is autogenerated by ojster template engine\n// usually there is no reason to edit it manually\n',

	useStrict: true,

	needCompactFragmentWhitespaces: true,
	indentStr: '\t',

	nonBlockFragmentsAreCode: true,

	thisAlias: 'self',
	funcLocals: 'var d = this.data, vars = this.vars;',

	funcStrs: {
		append: 'writer.write',
		escape: 'escape'
	},

	blockFuncNamePrefix: 'renderBlock',

	inherits: {
		alias: 'inherits',
		path: "'util'",
		subpath: 'inherits',
		fullName: undefined
	},

	css: {
		getCssNameFuncStr: 'getCssName',
		getCssNameFuncIsGlobal: false,
		baseCssNamePropStr: 'baseCssName',
		baseCssNamePropUseTypeHint: false,
		appendCssNamesLiterallyWhenPossible: false
	},

	appendLineNumbersFor: {
		require: false,
		template: false,
		inherits: false,
		func: true,
		funcEnd: true,
		baseCall: true,
		blockCall: true,
		templateInsertion: true,
		fragment: false,
		expression: true,
		sequenceClose: true,
		sequenceCloseBeforeBlockClose: false,
		oneLineCodeFragment: false
	}
};


module.exports = options;
