module.exports = {
	intro: '// Content below is autogenerated by ojster template engine\n// usually there is no reason to edit it manually\n',

	needCompactFragmentWhitespaces: true,
	indentStr: '\t',

	nonBlockFragmentsAreCode: true,

	thisAlias: 'self',

	funcStrs: {
		append: 'writer.write',
		escape: 'escape'
	},

	block: {
		locals: 'var d = this.data, vars = this.vars;',
		funcNamePrefix: 'renderBlock'
	},

	inherits: {
		alias: 'inherits',
		path: "'util'",
		subpath: 'inherits',
		fullName: undefined
	},

	css: {
		getCssNameFuncStr: 'getCssName',
		baseCssNamePropStr: 'baseCssName',
		appendCssNamesLiterallyWhenPossible: false
	},

	appendLineNumbersFor: {
		require: false,
		template: false,
		inherits: false,
		func: true,
		funcEnd: true,
		blockCall: true,
		templateInsertion: true,
		fragment: false,
		expression: true,
		sequenceClose: true,
		sequenceCloseBeforeBlockClose: false,
		oneLineCodeFragment: false
	}
};
