// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

goog.provide('ojster.example.templates.Hobbies');

goog.require('ojster'); // normally path will be just 'ojster'

ojster.example.templates.Hobbies = function() {
	ojster.Template.apply(this, arguments);
};
goog.inherits(ojster.example.templates.Hobbies, ojster.Template);

ojster.example.templates.Hobbies.prototype.renderBlockMain = function() { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>No hobbies detected.</div>'
	);
}; // @8:1

