// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

goog.provide('ojster.example.templates.Hobbies');

goog.require('ojster'); // normally here will be just 'ojster'

goog.scope(function() {

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {Object=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
ojster.example.templates.Hobbies = function() {
	ojster.Template.apply(this, arguments);
};
var Hobbies = ojster.example.templates.Hobbies;
goog.inherits(Hobbies, ojster.Template);

Hobbies.prototype.renderBlockMain = function() { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>No hobbies detected.</div>'
	);
}; // @8:1

}); // goog.scope
