// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('ojster.example.templates.Tools.SomeTool');
goog.provide('ojster.example.templates.Tools.SomeOtherTool');

goog.require('ojster'); // normally here will be just 'ojster'

goog.scope(function() {
"use strict";

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {Object=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
ojster.example.templates.Tools.SomeTool = function(opt_data, opt_ctx, opt_writer) {
	goog.base(this, opt_data, opt_ctx, opt_writer);
};
var SomeTool = ojster.example.templates.Tools.SomeTool;
goog.inherits(SomeTool, ojster.Template);
SomeTool.prototype.renderBlockMain = function() { // @5:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Some tool</div>'
	);
}; // @7:1

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {Object=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
ojster.example.templates.Tools.SomeOtherTool = function(opt_data, opt_ctx, opt_writer) {
	goog.base(this, opt_data, opt_ctx, opt_writer);
};
var SomeOtherTool = ojster.example.templates.Tools.SomeOtherTool;
goog.inherits(SomeOtherTool, ojster.Template);
SomeOtherTool.prototype.renderBlockMain = function() { // @11:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Other tool</div>'
	);
}; // @13:1

}); // goog.scope
