// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

goog.provide('ojster.example.templates.Tools.SomeTool');


goog.provide('ojster.example.templates.Tools.SomeOtherTool');

goog.require('ojster'); // normally here will be just 'ojster'

goog.scope(function() {

/** @constructor */
ojster.example.templates.Tools.SomeTool = function() {
	ojster.Template.apply(this, arguments);
};
var SomeTool = ojster.example.templates.Tools.SomeTool;
goog.inherits(SomeTool, ojster.Template);
SomeTool.prototype.renderBlockMain = function() { // @5:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Some tool</div>'
	);
}; // @7:1

/** @constructor */
ojster.example.templates.Tools.SomeOtherTool = function() {
	ojster.Template.apply(this, arguments);
};
var SomeOtherTool = ojster.example.templates.Tools.SomeOtherTool;
goog.inherits(SomeOtherTool, ojster.Template);
SomeOtherTool.prototype.renderBlockMain = function() { // @11:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<div>Other tool</div>'
	);
}; // @13:1

}); // goog.scope
