// Content below is autogenerated by ojster template engine
// usually, there is no reason to edit it manually

var inherits = require('util').inherits;
var Template = require('ojster/lib/template');

var Base = function() {
	Template.apply(this, arguments);
};
inherits(Base, Template);

Base.prototype.renderBlockMain = function() { // @6:1
	var self = this;
	var d = this.data, vars = this.vars;
	self.writer.write(
		'<html><head>'
	); // @9:1
	self.renderBlockMeta();
	self.writer.write(
		'<title>'
	); // @10:8
	self.renderBlockTitle();
	self.writer.write(
		'</title>'
	); // @11:1
	self.renderBlockCss();
	self.renderBlockScript();
	self.writer.write(
		'</head><body>'
	); // @14:7
	self.renderBlockContent();
	self.writer.write(
		'</body></html>'
	);
	return this;
}; // @16:1

Base.prototype.renderBlockMeta = function() { // @9:1
	var self = this;
	var d = this.data, vars = this.vars;
	return this;
};

Base.prototype.renderBlockTitle = function() { // @10:8
	var self = this;
	var d = this.data, vars = this.vars;
	return this;
};

Base.prototype.renderBlockCss = function() { // @11:1
	var self = this;
	var d = this.data, vars = this.vars;
	return this;
};

Base.prototype.renderBlockScript = function() { // @12:1
	var self = this;
	var d = this.data, vars = this.vars;
	return this;
};

Base.prototype.renderBlockContent = function() { // @14:7
	var self = this;
	var d = this.data, vars = this.vars;
	return this;
};

module.exports = Base;
