// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
// templates designed exclusively for node do not need fully qualified names


// variables can be safely defined at any place
// they are bound to produced module only
var tmp;

// the same is true for functions
function abc() {
	return 'abc';
}


// @require needs path and optional subpath as defined below
var ojster = require('ojster'); // equivalent to: ojster = 'ojster'
var MyLib = require('./my_lib');

// @template and @inherits need alias only
var Base = function(opt_data, opt_ctx, opt_writer) {
	ojster.Template.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Base, ojster.Template);


// any code within and outside of blocks can use any of aliases defined above
var tmp1 = Base.prototype;


Base.prototype.renderBlockMain = function() { // @27:1
	var self = this;
	var d = this.data, vars = this.vars;
};

module.exports = Base;
