// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
goog.provide('ojster.examples.templates.Base');

goog.require('ojster');
goog.require('ojster.examples.somemodule');


// goog.scope will be started right before template definition
// any aliases defined above can be used within scope,
// because they will be explicitly defined

goog.scope(function () {
"use strict";

var SomeClass = ojster.examples.somemodule.sub.SomeClass;

/**
 * @param {Object=} opt_data
 * @param {Object=} opt_ctx
 * @param {ojster.StringWriter=} opt_writer
 * @constructor
 * @extends {ojster.Template}
 */
ojster.examples.templates.Base = function (opt_data, opt_ctx, opt_writer) {
	ojster.examples.templates.Base.base(this, 'constructor', opt_data, opt_ctx, opt_writer);
};
var Base = ojster.examples.templates.Base;
goog.inherits(Base, ojster.Template);


// it is safe to define any variables within scope,
// they will not be available outside

var tmp = Base.prototype; // using alias
var tmp1 = ojster.examples.templates.Base; // fully qualified names can be used as well


Base.prototype.renderBlockMain = function () { // @20:1
	var self = this;
	var d = this.data, vars = this.vars;

		var tmp = ojster.Template.prototype;
		var tmp1 = ojster.Template;

}; // @25:1


// goog.scope will be closed at the end of file


}); // goog.scope
