// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually

goog.provide('ojster.example.templates.Base');

goog.require('ojster');

ojster.example.templates.Base = function() {
	ojster.Template.apply(this, arguments);
};

// goog.scope will be started rigth after template definition
// any aliases defined above can be used within scope,
// because they will be explicitly defined

goog.inherits(ojster.example.templates.Base, ojster.Template);


// it is safe to define any variables within scope,
// they will not be available outside

var tmp = Base.prototype; // using alias
var tmp1 = ojster.example.templates.Base; // fully qualified names can be used as well


ojster.example.templates.Base.prototype.renderBlockMain = function() { // @19:1
	var self = this;
	var d = this.data, vars = this.vars;

        var tmp = ojster.Template.prototype;
        var tmp1 = ojster.Template;
    
}; // @24:1


// goog.scope will be finished at the end of file


